### ISSUE TITLE
Cannot read properties of null (reading 'removeChild')

### ISSUE THREAD

**Issue by probablykasper** [romkor/svelte-portal#127]
I'm using svelte-portal for a modal with a `Create` button. When `Create` is clicked, it goes to a new page which has a different `__layout.svelte`. When this happens, this error is thrown:
```
Uncaught TypeError: Cannot read properties of null (reading 'removeChild')
    at detach (index.mjs:373:21)
    at detach_dev (index.mjs:2004:5)
    at Object.destroy [as d] (Nav.svelte:139:8)
    at index.mjs:1141:27
    at run (index.mjs:18:12)
    at Array.forEach (<anonymous>)
    at run_all (index.mjs:24:9)
    at Object.c (index.mjs:1339:37)
    at index.mjs:175:19
    at Set.forEach (<anonymous>)
```

**Comment by romkor** [comment]
Can you attach some code or link to repl please

**Comment by probablykasper** [comment]
Yes, here's a reproduction repo: https://github.com/probablykasper/portal-removechild-bug

**Comment by probablykasper** [comment]
Huh, weird how that would fix it. It's just the same code, but using an external component, right?

**Comment by romkor** [comment]
Yes, completely agree, its weird
