### ISSUE TITLE
Type definitions missing

### ISSUE THREAD

**Issue by m93a** [romkor/svelte-portal#128]
When I try to import the package in my Svelte project, I get the following error:
```
Could not find a declaration file for module 'svelte-portal'.
'node_modules/svelte-portal/src/main.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/svelte-portal` if it exists or add a new declaration (.d.ts) file containing `declare module 'svelte-portal';`
```
Looking at the svelte-portal folder in node_modules, there indeed isn't any `.d.ts` file.

This is weird, `sveltekit package` should produce both a compiled `.svelte` file as well as `.d.ts` file. (For comparison, projects like [`svelte-material-ui`](https://sveltematerialui.com/) do ship the `.d.ts` files, and therefore work out-of-the-box.) Could you, by any chance, publish the package *with* the type definitions?

**Comment by m93a** [comment]
I've created a new SvelteKit project and copypasted `Portal.svelte` there.
It does the trick, now it includes the type definitions.
You can check [my fork](https://github.com/m93a/svelte-portal/), or get it [from NPM](https://www.npmjs.com/package/@m93a/svelte-portal).

**Comment by romkor** [comment]
Did you try import Portal from “svelte-portal/src/Portal.svelte”?

**Comment by romkor** [comment]
Trick is to keep backward compatibility for javascript users. Maybe it can be good idea just add types definition by hands))

**Comment by romkor** [comment]
PR with `Portal.svelte.d.ts` file will be useful.
Thanks!

**Comment by m93a** [comment]
Sorry for the delay! I've created PR #135.

**Comment by romkor** [comment]
Thanks, merged!
