### ISSUE TITLE
Build the package before publishing on npm

### ISSUE THREAD

**Issue by johannchopin** [romkor/svelte-portal#14]
Hey @romkor 👋 

I use your useful svelte component in one of my project [gitmoji-browser-extension](https://github.com/johannchopin/gitmoji-browser-extension). But sadly your package on npm contain the `.svelte` component directly. Is it possible to have it build on npm?

**Comment by romkor** [comment]
Hey @johannchopin!
Will try look at it soon.

**Comment by johannchopin** [comment]
Hey did you make some progress on this one? 😅

**Comment by romkor** [comment]
Sorry for laaaate response.
Not sure, I understand why you need builded version of svelte-portal.

**Comment by romkor** [comment]
Svelte compiler will compile svelte and related libs during building your project.
