### ISSUE TITLE
Check if target is string or DOM node

### ISSUE THREAD

**Issue by frederikhors** [romkor/svelte-portal#3]
Can we check if `target` is a string or a DOM node?

In case it's string we can do `document.getElementById(target)`.

Is it a bad idea?

**Comment by romkor** [comment]
>Can we check if target is a string or a DOM node?

Yes, for some cases it can be useful.

>In case it's string we can do document.getElementById(target).

`document.querySelector(target)` is more flexible

**Comment by romkor** [comment]
String target is available in the new version
