### ISSUE TITLE
Update or replace?

### ISSUE THREAD

**Issue by AlgoTrader** [romkor/svelte-portal#34]
I have a question, Portal adds new content to some element, but I would like to get replacing. I have a DOM element that can be shared among many `<Portal>` tags. 

Is it possible that every new Portal render just replaces the content of the DOM element but not just adds there?

**Comment by romkor** [comment]
It's not possible with current implementation, because Portal is inserted in target using `appendChild`.
Replace can be a bit hard because of need to destroy svelte components before replacing them to avoid memory leaks.

**Comment by AlgoTrader** [comment]
There is no need to destroy the component immediatly. I copied the code and added just three lines. I clean all the dom children before appendChild. It works, but does not look clean. Then component leave anyway. Any ideas?

**Comment by AlgoTrader** [comment]
II have situation when several portals compete for the single target, the last one wins. I have to control it.

**Comment by johannchopin** [comment]
@AlgoTrader It's possible in Svelte but I guess it's not the intend of a Portal so this feature would be a little off-topic for this component.

**Comment by romkor** [comment]
>I clean all the dom children before appendChild
@AlgoTrader it can lead to memory leaks if you just remove all inner elements including svelte rendered components.

**Comment by romkor** [comment]
As I said current implementation of svelte-portal do not allow you safely replace target's content. And I do not plan to add this feature in near future, so I will close this issue.
